Vagrant.configure("2") do |config|
  
  # Web Server 1 - Ubuntu 20.04
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/focal64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.41"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

  # Web Server 2 - Ubuntu 20.04
  config.vm.define "web02" do |web02|
    web02.vm.box = "ubuntu/focal64"
    web02.vm.hostname = "web02"
    web02.vm.network "private_network", ip: "192.168.56.42"
    web02.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

  # Database Server - CentOS 7
config.vm.define "db01" do |db01|
  db01.vm.box = "centos/7"
  db01.vm.hostname = "db01centos7"
  db01.vm.network "private_network", ip: "192.168.56.43"
  
  db01.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  # Provisioning block for installing and setting up MariaDB
  db01.vm.provision "shell", inline: <<-SHELL
    yum install -y wget unzip mariadb-server
    systemctl start mariadb
    systemctl enable mariadb
  SHELL
end


end
